import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { prisma } from "@/lib/prisma";
import { getCurrentOrganization } from "@/lib/tenant";
export async function GET(_: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await ctx.params;
    const sb = await createClient();
    const { data: { user } } = await sb.auth.getUser();
    if (!user) return new NextResponse("Unauthorized", { status: 401 });
    const org = await getCurrentOrganization();
    if (!org) return new NextResponse("Not found", { status: 404 });
    const po = await prisma.purchaseOrder.findFirst({ where: { id, organizationId: org.id }, include: { lineItems: true, supplier: true, organization: true } });
    if (!po) return new NextResponse("PO not found", { status: 404 });
    const fmt = (n: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: po.currency || "INR" }).format(n);
    const dt = (d: any) => d ? new Date(d).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "—";
    const rows = (po.lineItems || []).map((li: any, i: number) => `<tr><td>${i+1}</td><td>${li.description||"—"}</td><td style="text-align:center">${li.quantity??1}</td><td style="text-align:right">${fmt(li.unitPrice??0)}</td><td style="text-align:center">${li.glAccount||"—"}</td><td style="text-align:right">${fmt(li.lineTotal??0)}</td></tr>`).join("");
    const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><title>PO ${po.poNumber}</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:Arial,sans-serif;font-size:11px;color:#1a1a1a;padding:40px;max-width:900px;margin:auto}.hdr{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:32px;border-bottom:3px solid #1A2A52;padding-bottom:20px}.logo{font-size:22px;font-weight:900;color:#1A2A52}.logo-sub{font-size:9px;color:#C8A04D;letter-spacing:2px;text-transform:uppercase;margin-top:2px}.po-h{text-align:right}.po-h h1{font-size:28px;font-weight:900;color:#1A2A52}.po-num{font-size:13px;color:#C8A04D;font-weight:700;margin-top:4px}.badge{display:inline-block;padding:3px 10px;border-radius:20px;font-size:9px;font-weight:700;text-transform:uppercase;margin-top:8px;background:#dbeafe;color:#1e40af}.meta{display:grid;grid-template-columns:1fr 1fr 1fr;gap:20px;margin-bottom:28px}.mb{background:#f8f9fb;border-radius:8px;padding:14px}.mb label{font-size:9px;font-weight:700;color:#9ca3af;text-transform:uppercase;letter-spacing:.8px;display:block;margin-bottom:6px}.mb p{font-size:11px;font-weight:600;color:#111827;line-height:1.5}.mb small{font-size:10px;color:#6b7280}table{width:100%;border-collapse:collapse;margin-bottom:20px}thead tr{background:#1A2A52;color:white}thead th{padding:10px 12px;text-align:left;font-size:9px;font-weight:700;text-transform:uppercase}tbody tr:nth-child(even){background:#f9fafb}tbody td{padding:9px 12px;border-bottom:1px solid #e5e7eb;font-size:10px;color:#374151}.tots{display:flex;justify-content:flex-end;margin-bottom:28px}.tots-box{width:280px}.tr{display:flex;justify-content:space-between;padding:6px 0;border-bottom:1px solid #e5e7eb;font-size:10px}.tr.grand{font-weight:700;font-size:12px;color:#1A2A52;border-bottom:none;padding-top:10px}.terms{background:#f0f4ff;border-radius:8px;padding:14px;margin-bottom:24px}.terms label{font-size:9px;font-weight:700;color:#1A2A52;text-transform:uppercase;display:block;margin-bottom:6px}.terms p{font-size:10px;color:#374151;line-height:1.6}.ftr{display:flex;justify-content:space-between;border-top:2px solid #e5e7eb;padding-top:20px}.sig{text-align:center}.sig-line{width:160px;border-bottom:1.5px solid #374151;margin-bottom:6px;height:36px}.sig p{font-size:9px;color:#6b7280}.sig strong{font-size:10px;color:#111827}</style></head><body>
<div class="hdr"><div><div class="logo">Veltriance</div><div class="logo-sub">Technologies LLP</div><div style="margin-top:10px;font-size:10px;color:#6b7280;line-height:1.6">Procurement Platform<br/>${po.organization?.name||"Ace Technologies India"}</div></div><div class="po-h"><h1>PURCHASE ORDER</h1><div class="po-num">${po.poNumber}</div><div><span class="badge">${po.status||"DRAFT"}</span></div></div></div>
<div class="meta"><div class="mb"><label>Supplier</label><p>${po.supplier?.name||"—"}</p><small>${po.supplier?.code||""}<br/>${po.supplier?.contactEmail||""}</small></div><div class="mb"><label>Delivery</label><p>${po.deliveryLocation||"To be confirmed"}</p><small>Required: ${dt(po.requiredDate)}</small></div><div class="mb"><label>PO Details</label><p>Issued: ${dt(po.issuedAt||po.createdAt)}</p><small>Payment: ${po.paymentTerms||po.supplier?.paymentTerms||"Net 30"}<br/>Currency: ${po.currency||"INR"}</small></div></div>
<table><thead><tr><th style="width:4%">#</th><th style="width:40%">Description</th><th style="width:8%;text-align:center">Qty</th><th style="width:14%;text-align:right">Unit Price</th><th style="width:10%;text-align:center">GL A/c</th><th style="width:14%;text-align:right">Total</th></tr></thead><tbody>${rows||'<tr><td colspan="6" style="text-align:center;color:#9ca3af;padding:20px">No line items</td></tr>'}</tbody></table>
<div class="tots"><div class="tots-box"><div class="tr"><span>Subtotal</span><span>${fmt(po.subtotal??0)}</span></div><div class="tr"><span>GST (18%)</span><span>${fmt(po.totalTax??0)}</span></div><div class="tr grand"><span>Total Amount</span><span>${fmt(po.totalAmount??0)}</span></div></div></div>
<div class="terms"><label>Terms & Conditions</label><p>1. This PO is subject to the standard terms and conditions of ${po.organization?.name||"Ace Technologies India"}.<br/>2. Goods/services must match specifications. Deviations require written approval.<br/>3. Invoice must reference PO number ${po.poNumber}. Payment per agreed terms.<br/>4. Supplier accepts responsibility for quality, compliance, and timely delivery.</p></div>
<div class="ftr"><div class="sig"><div class="sig-line"></div><strong>Authorised by</strong><p>Procurement Team</p></div><div style="text-align:center;font-size:9px;color:#9ca3af;align-self:flex-end">Generated by Veltriance Procurement Platform<br/>System-generated document — ${new Date().toLocaleDateString("en-IN")}</div><div class="sig"><div class="sig-line"></div><strong>Supplier Acknowledgement</strong><p>${po.supplier?.contactName||"Supplier Representative"}</p></div></div>
</body></html>`;
    return new NextResponse(html, { headers: { "Content-Type": "text/html; charset=utf-8", "Content-Disposition": `attachment; filename="PO-${po.poNumber}.html"` } });
  } catch (e: any) { return new NextResponse("Error: " + e?.message, { status: 500 }); }
}
